name: Scott Fickas
favicon: null
layout_spectrum: 0.27196633047424257
typography_spectrum: 0.4569313882384449
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.42244287114590406
  lightness: 0.7112531629391015
  saturation: 0.8216615587007254
  rhythmicContrast: 0.6402485023718327
purpose: []
